### ISSUE TITLE
QR code not showing up on pebble time steel with Gadgetbridge.

### ISSUE THREAD

**Issue by john453** [reini1305/qrgenerator#3]
Hi there,

I am curious as to how this app works.
- Does this app need internet connection to generate the QR code before it appear on the pebble?
- Does it need the default pebble app to work properly on my pebble, as i am using an alternative app called 'Gadgetbridge instead of the default pebble app?

The problem i am having is that once i configure the QR details needed, it does not show the actual QR on the pebble but shows a black white screens instead, although it scrolls part of the details i had entered in configuration screen below the 'QR Generator' name and icon on the pebble menu where all the installed app on the pebble are.

Thanks  :smile:

**Comment by reini1305** [comment]
Hi! QR Generator does not need internet connection, however, the code is created by JS on the phone. I have never used GadgetBridge so I can't answer your question. Can you attach a picture of the "black and white screens" of the watch?

**Comment by john453** [comment]
![screen-1](https://cloud.githubusercontent.com/assets/17296419/19776309/136ae460-9c63-11e6-85c8-80fc8a2a79c0.png)

screen-1 is how it shows up in the pebble installed app menu

**Comment by john453** [comment]
![screen-2](https://cloud.githubusercontent.com/assets/17296419/19776449/a694811a-9c63-11e6-9262-599e5b622004.png)

screen-2 is how it shows up in when i click on the app ie QR Generator

note that screen-2 is how it shows up but without the pebble black boarders.

**Comment by reini1305** [comment]
It seems like the watch is only receiving the description, but not the QR code itself. Does GadgetBridge allow to capture some logs? My javascript code outputs a few debug messages that can be intercepted using the original Pebble app.

**Comment by john453** [comment]
i believe you can capture logs so will try and post that.

However, just for comparison - the QR from this app shows up on my pebble -
https://apps.getpebble.com/en_US/application/5455a2d633c8649b4000002b

**Comment by john453** [comment]
heres a pic from the same pebble with the **Dunkin Gift Card Keeper** _QR code_ showing up okay.
![dunkin gift card keeper](https://cloud.githubusercontent.com/assets/17296419/19776863/51073f7e-9c65-11e6-8bac-f6849d5a721e.png)

**Comment by reini1305** [comment]
This app might be calculating the QR code directly on the watch. Can't say without access to the source code.

**Comment by john453** [comment]
yes i believe that app is indeed calculating the QR code on the pebble as you can change the 4x4 16 digit code and this changes the QR code on the fly.

**Comment by reini1305** [comment]
I'm not planning on changing the working  principle QR Generator anytime soon (however I would approach it differently when I would start now). Let's see what your logs can tell us about this issue.

**Comment by john453** [comment]
That ok then, as if the Dunkin Gift Card Keeper app calculates the QR Code on the pebble, that means **your app uses the default pebble app** to do the same, so if it's not working for me ie someone who doesnt use the default pebble app, then **the problem is with how Gadgetbridge handles the same**.

Thanks for comments & help though :smile:

**Comment by john453** [comment]
[gadgetbridge.log.txt](https://github.com/reini1305/qrgenerator/files/556593/gadgetbridge.log.txt)

Attached is the log file you requested.

I believe that the problem might be on this line in the log:-

`18:28:51.110 [JavaBridge] WARN  n.f.g.u.GB - Discarded key qrcode, not found in the local configuration and is not an integer key.`

**Comment by reini1305** [comment]
Strange one. I checked, and there is nothing special with the key qrcode. I guess it won't work with GadgetBridge then. But thanks for checking and being so cooperative!

**Comment by john453** [comment]
thanks too, maybe the Gadgetbridge guys can figure it out :+1:

**Comment by john453** [comment]
just to let you know, it was a bug within Gadgetbridge (_brought to the fore by QR Generator_) and it has now been fixed, so this issue can be closed.

Thanks for your assists :smile:

**Comment by reini1305** [comment]
Nice!
