### ISSUE TITLE
Hide empty codes

### ISSUE THREAD

**Issue by PonyOny** [reini1305/qrgenerator#4]
It would be nice to hide the empty values in the pebble app so if you only have one QR codo for personal contact card just show one QR code on the watch instead of showing all the other empty ones, it would allso be nice to add a title to the custom qr text codes instead of showing the real text, lile Wifi Home and not show the wifi password as title.

**Comment by reini1305** [comment]
Hi!

Empty codes are actually hidden (or jumped over) on the watch. I'm not really fluent in web technologies so I don't know how to do this in the configuration.

Description is added to the TODO list :)
